### ISSUE TITLE
HUD not working with FireFox recently

### ISSUE THREAD

**Issue by loritempleton** [zaproxy/zap-hud#1135]
We use Zap on a regular basis with FF, A few weeks ago I ran my scans fine.  But today, I can't get the "Heads Up Display" to work on Firefox.  It works on Chrome.  My whole QA team reported the same experience.  Upon further investigation seems Zap is throwing an error in the console for Firefox ( see image):

![8-11-22ZapError](https://user-images.githubusercontent.com/72763700/184198647-7f0b5b7f-713a-4918-aad8-b88f3ceed0fb.png)

BTW I'm not operating in Private Browser mode.   My current version of FF is on a MAC. 103.0.2 (64-bit). ANy idea on if something changed in FF blocking the HUD recently?

**Comment by thc202** [comment]
Yes, something changed and the HUD no longer works with Firefox, the cause is being investigated.

**Comment by psiinon** [comment]
Just to make this clear - something changed in Firefox :/
Chrome still works as a workaround, but being a Mozillian I'm keen to get it working on Firefox again...

**Comment by psiinon** [comment]
@loritempleton can you try changing your Firefox settings - under Privacy and Security, scroll down to Cookies and Site Data, click on "Manage Exceptions...", type `https://zap/` in the Address of Website section and click `Allow` then `Save Changes`.
Then reload the page with the HUD on. That worked for me.
Unfortunately that has to be done every time you launch Firefox from ZAP right now - I'll see if theres a way we can get ZAP to apply that setting automatically...

**Comment by psiinon** [comment]
Asked for help on the Mozilla Discourse: https://discourse.mozilla.org/t/failed-to-register-update-a-serviceworker/102538

**Comment by psiinon** [comment]
See this thread on twitter: https://twitter.com/psiinon/status/1558070292433567750
This is proving painful ☹️

**Comment by Anthonymcqueen21** [comment]
I use FoxyProxy when i work with Zap it connects i did the steps you mentioned but for some reason my HUD is not showing and its not catching any possible alerts. I dont understand why is the new update just not working with FireFox ?

**Comment by kingthorin** [comment]
1. If you aren't launching the browser from ZAP them you could be missing settings for HUD.
2. If you haven't browsed to a site it won't show (it doesn't display on about:blank).

**Comment by psiinon** [comment]
@Anthonymcqueen21 what version of Firefox are you using?
Are there any errors in the zap.log file? 
https://www.zaproxy.org/faq/somethings-not-working-what-should-i-do/#check-the-log-file

**Comment by Anthonymcqueen21** [comment]
I am using the default settings for that and the latest version of firefox

**Comment by kingthorin** [comment]
> Are there any errors in the zap.log file? https://github.blog/changelog/2022-10-06-express-disinterest-on-for-you-feed-rollup-items/

**Comment by psiinon** [comment]
Thanks for letting us know!
