### ISSUE TITLE
Use WebSocket channel for API requests

### ISSUE THREAD

**Issue by thc202** [zaproxy/zap-hud#130]
The log events are currently sent to ZAP with HTTP, which means more resources are used than if sent through the WebSocket channel. Is there any reason not to use that instead?

Sample HTTP request:
```
GET https://zap//zapCallBackUrl/-4262183702902603983/hud/action/log/?record=00:00:00%20GMT+0000%20(WEST)%20INFO%20heartbeat:%20heartbeat HTTP/1.1
Host: zap
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://zap//zapCallBackUrl/-3596693309352194563?name=management.html
origin: https://zap
Connection: keep-alive
```

**Comment by psiinon** [comment]
Working on this now:

- [ ] Active scan
- [ ] Attack mode
- [ ] Break
- [ ] History
- [ ] Logging
- [ ] Scope
- [ ] Sites tree
- [ ] Spider
- [ ] Show welcome screen option

**Comment by psiinon** [comment]
All done, apart from the welcome screen option that I'm proposing gets fixed once the start up has stabilised.
The option doesnt work right now anyway so I'm disabled the checkbox.
