### ISSUE TITLE
Lint all JavaScript

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#26]
Ideally should run on all PRs

- http://www.javascriptlint.com/
- https://github.com/reid/node-jslint

Not investigated yet...

**Comment by bkimminich** [comment]
I'd recommend https://standardjs.com for linting, as it offers auto-fixing of issues and you get rid of those incredibly annoying and useless semicolons once and for all... 😁 

I'm using it on the Juice Shop since ... forever ... and it worked fine on backend and frontend JS alike. Never ran into any interpreter issues with it, and it looks really pretty.

**Comment by psiinon** [comment]
OK, we should really revisit this.
Lets go with https://standardjs.com/ since it has less configuration and auto fixes.
Any objections?
@dscrobonia @thc202 @kingthorin anyone else?

**Comment by kingthorin** [comment]
Seems fine to me. 
It comes with a [recommendation](https://github.com/zaproxy/zap-hud/issues/26#issuecomment-443993383), and requires little to no config.

**Comment by Pamplemousse** [comment]
I remember @dscrobonia using [`xo`](https://github.com/xojs/xo).
There was an issue about chosing a style guide already: #24 .

**Comment by dscrobonia** [comment]
Oh ya! Thanks for the reminder @Pamplemousse . I forgot I had already configured a linter 😅 . @psiinon if you run `npm run lint`  `xo` will start linting.

You can also run `npm install --global xo` to install xo. And then run `xo --fix` to do the automatic fixes.

![image](https://user-images.githubusercontent.com/5150944/61497534-9d304e80-a974-11e9-8757-bf56f3542029.png)

**Comment by dscrobonia** [comment]
Running the automatic fixes takes us down to just 1000 errors. haha.
![image](https://user-images.githubusercontent.com/5150944/61497578-c51fb200-a974-11e9-9f52-36ec4bfa0725.png)

**Comment by psiinon** [comment]
So how do we get linting and formatting applied to the HUD JS code?
TBH I dont really mind which one we use, as long as we use something.
@dscrobonia can you submit a PR? I dont think we need zero errors, but we do want the code formatted and to be able to see the lint errors.

**Comment by psiinon** [comment]
I've just tried both of them. When Xo is set to use prettier then they both so essentially the same thing.
The only obvious difference is that Xo has a ton more options .. but I'm not sure thats a good thing, I like the simplicity of StandardJS - we just use it as is. But in the end I dont really mind, I'd just like it applied asap.
I'm happy to submit a PR but if I do it will probably be for StandardJS, so if you'd like us to use Xo please submit a PR asap :)

**Comment by bkimminich** [comment]
I don't know Xo but I can vouch for. StandardJS producing some really pretty code and *no nasty semicolons* by default! 👍

**Comment by jaywon** [comment]
I'd like to just caution, and not speaking from a very personal point of view but just experience in enforcing opinions that StandardJS and enforcing those opinions can have side effects, and no semi colons is very much an opinion that does have some side effects people must know about. 

Not my intent at all to debate that as the purpose of this thread (nor is it a personal pov per se), but something that enables first (`xo`) vs enforce first (`standardjs`) generally has less tension over time in my experience.  

They detail some of the gotchas here (and a very pointed response to a counter argument 😱 ):
[https://standardjs.com/rules.html#semicolons]

This project is still a bit raw in terms of tooling and architecture/best practices and so the justifications about AST based minifiers catching this (so developers shouldn't worry) also assumes some level of standardization around *all* of the tools and this project still is trying to get to that point.

I think, to me, it just feels better to implement with least resistance first and then tweak rules over time, and even that is something that is configurable if decided upon. $.02. 😃

**Comment by psiinon** [comment]
Fixed by https://github.com/zaproxy/zap-hud/pull/604
