### ISSUE TITLE
Alert flags on fields with issues no longer work

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#290]
To reproduce scan the bodgeit search page to find the XSS. The search field is correctly highlighted and an icon is added, but clicking on that icon has no effect.
An error is shown in the console:
```
17:14:39 GMT-0500 (Eastern Standard Time) ERROR errorHandler: TypeError: json.alert is undefined
	 showAlertDetails    https://zap//zapCallBackUrl/-8471248859937673292?name=tools/utils/alertUtils.js 103:: {}
```

**Comment by psiinon** [comment]
Looks like its calling the API endpoint `/core/view/alert/?id=undefined` ;)

**Comment by psiinon** [comment]
@dscrobonia I think the bug is that https://github.com/zaproxy/zap-hud/blob/develop/src/main/zapHomeFiles/hud/tools/commonAlerts.js#L55 isnt including the tabId, unlike https://github.com/zaproxy/zap-hud/blob/develop/src/main/zapHomeFiles/hud/tools/commonAlerts.js#L71

The trouble is the message originates from inject.js: https://github.com/zaproxy/zap-hud/blob/develop/src/main/zapHomeFiles/hud/target/inject.js#L266 which doesnt appear to have access to the tabId. Will we need to pass that in or is there a better way?

**Comment by dscrobonia** [comment]
ah! yah that is the bug. and the inject does have access to the tabId, because it generated it! https://github.com/zaproxy/zap-hud/blob/develop/src/main/zapHomeFiles/hud/target/inject.js#L13

:) good find
