### ISSUE TITLE
Scan specific url

### ISSUE THREAD

**Issue by nagpradis** [zaproxy/zap-hud#299]
Hi all -

I started using HUD with ZAP and it has been a great experience. Very efficient way to do the manual testing. My request is, it would be great to give a button that can trigger an active scan on the intercepted request. 

Thanks!
Nagpradis

**Comment by psiinon** [comment]
Thanks for the feedback!
Definitely agree with the option to scan a specific url, I can see that being very useful

**Comment by dscrobonia** [comment]
Agreed. Excited to see it!
