### ISSUE TITLE
Sites upgraded to https fail if 'only in scope' switched on

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#316]
Start using the HUD with an HTTP based site, but dont add it to the scope. The HUD will upgrade it to HTTPS.
Turn on the 'Enable the HUD only for URLs that are in scope' option.
The site will then fail with "Unrecognized SSL message, plaintext connection?" errors.
This is pretty confusing, especially for newcomers.
(Thanks mum: https://twitter.com/psiinon/status/1077890840142450689 ;)

**Comment by dscrobonia** [comment]
Great find! More usability tests!

**Comment by manteca** [comment]
Got the same error problem.
Error message:

> An exception occurred while attempting to connect to: https://localhost:5000/login/
The exception was: 
Remote host closed connection during handshake
Root cause: 
EOFException: SSL peer shut down incorrectly

I disable the option 'Enable the HUD only for URLs that are in scope' and everything work again.

ZAP v.2.8.0
