### ISSUE TITLE
HUD unresponsive if you wait on the welcome screen

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#342]
Launch a browser with the welcome screen enabled, and leave it for a couple of mins.
Dismiss the screen and you'll find that the HUD doesnt communicate with ZAP - no alerts etc.
It looks like the hearbeats are failing because navigator.serviceWorker.controller is null.
@dscrobonia is this because the serviceworker isnt really active until we refresh?
If so we might need to change how the Welcome screen works, unless your startup revamp will address this?

**Comment by dscrobonia** [comment]
ahh. So the serviceworker is `active` in the Service Worker lifecycle meaning. BUT the heartbeat doesn't start until the pages get refreshed. so if you wait for a while the servieworker will terminate.

Startup fixes will help this. We can refresh in the background so taht the heartbeat works.

**Comment by psiinon** [comment]
This will be a blocker to #341 but not super urgent
