### ISSUE TITLE
History displays upgraded URL's, not original http URL's

### ISSUE THREAD

**Issue by dscrobonia** [zaproxy/zap-hud#353]
I think the history tool should display the original URL of pages that have been upgraded to https from http. Thoughts? 

You can see in this screen shot that we actually currently see both the original http request, and then the upgraded request.
![image](https://user-images.githubusercontent.com/5150944/51078109-1026d880-1665-11e9-959d-ab372000e463.png)

**Comment by psiinon** [comment]
I'm confused.
Its showing the original http requests for localhost, which is right, no?
The upgrade from http -> https for owasp.org is being done by owasp.org not the HUD - just try it in your browser (without the HUD) to see.

**Comment by dscrobonia** [comment]
oh no you're totally right. hahaha. bad instant reaction.
