### ISSUE TITLE
Show websockets messages in new tab

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#373]
Similar (and next) to the history tab and as per the desktop Websockets tab.
I'm thinking that this should only show websockets messages to the current site being displayed? Or is that an option we give to users?
This work can be phased:

- [x] New tab showing websockets messages
- [x] Select message to display and resend
- [x] Option to resend message
- [ ] Support break with websockets

This will require some changes to the ZAP websockets add-on

**Comment by psiinon** [comment]
For info I've just got the websockets messages being shown in a new tab, although they could be prettier ;)

**Comment by dscrobonia** [comment]
> I'm thinking that this should only show websockets messages to the current site being displayed? Or is that an option we give to users?

Whatever route we go with here lets keep it consistent to how we're treating http messages. I think my default both http and websocket histories should only show traffic for the site/tab that you're in, and then there should be an easy checkbox to display traffic across all tabs. I want to say this isn't a trivial fix, but as a user I think that's how I would want to experience it.

**Comment by jaywon** [comment]
This is possibly a new way to think about "scopes" and how they're defined/experienced?

**Comment by dscrobonia** [comment]
Ya I've actually been thinking about that quite a bit. In some tools we run them against the domain/url we're currently in and don't actually use the scope. And our notion of "scope" in the HUD hadn't previously supported multiple domains, urls, or regexes yet. I started making progress towards that in #350 by trying to treat scope as a list of urls. But lots more needed to be done.

Ideally things like history, websocket I think should the current tab only by default. But that there should be filters for "all traffic" and "in scope traffic"
