### ISSUE TITLE
HUD fails with Java 11 and TLS 1.3

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#392]
Java "11.0.2" 2019-01-15 LTS
Getting error code SSL_ERROR_RX_RECORD_TOO_LONG in the console.
Reported by @mozmark

**Comment by psiinon** [comment]
We're retrying with Java 8, but didnt want this problem forgotten about.

**Comment by thc202** [comment]
This is most likely a JRE issue, we workaround it in the tests by disabling TLS 1.3 (in Options > Proxy).

**Comment by psiinon** [comment]
For info Java 8 works fine on that machine :)

**Comment by psiinon** [comment]
/me wonders if we can detect that anywhere and then give a user friendly warning

**Comment by mozmark** [comment]
Curious; do we have any more info on what's happening here? Do TLS 1.3 bugs affect other apps on Java 11?

**Comment by thc202** [comment]
I don't have details of the actual problem yet. They should, there are a couple of TLS 1.3 related bugs:
https://bugs.openjdk.java.net/browse/JDK-8217709?jql=project%20%3D%20JDK%20AND%20issuetype%20%3D%20Bug%20AND%20text%20~%20%22TLS%201.3%22%20ORDER%20BY%20affectedVersion%20DESC
(I didn't find any that matches this case though.)

**Comment by psiinon** [comment]
Yep, burp :) https://twitter.com/burp_suite/status/1098136754425495553

**Comment by kingthorin** [comment]
Well good to know we're not alone.

**Comment by psiinon** [comment]
Note that TLS 1.3 is now disabled by default in ZAP, so hopefully we'll see this less often.

**Comment by raulsiles** [comment]
Burp 2020.4 added support for TLS 1.3 via Java 13 a few days ago:
https://portswigger.net/burp/releases/professional-community-2020-4
"Provided you have Java 13, Burp Proxy now supports TLS 1.3."

The TLS 1.3 connection testing can be done with the following TLS 1.3-only website:
https://tls13.1d.pw

A connection attempt to this same site, using ZAP 2.9.0 in normal mode (not HUD), after enabling TLS 1.3 in "options - Local Proxies", and using the same Java 13 VM fails with a 502 error:
```
An exception occurred while attempting to connect to: https://tls13.1d.pw/
The exception was: 
Received fatal alert: protocol_version
Root cause: 
SSLHandshakeException: Received fatal alert: protocol_version
```

**Comment by thc202** [comment]
You need to enable in Options > Connection > Security Protocols instead. That just affects the client side.

**Comment by raulsiles** [comment]
I can confirm ZAP is working fine when accessing a TLS 1.3-only website using Java 13.0.2 (Windows, for the record). I have also tested HUD works fine with this setup. Therefore, this issue might potentially be closed and recommend using ZAP with Java 13 vs. Java 11 for TLS 1.3 connections.

**Comment by thc202** [comment]
The recommendation should not be necessary, latest versions of Java 11 (e.g. 11.0.7) work fine with the HUD.
