### ISSUE TITLE
HTTP Message dialog shows JSON as [object Object]

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#433]
Select an HTTP message with a JSON body from the History tab.
The body will be shown as:

> [object Object]

Rather than the actual JSON data.

**Comment by dscrobonia** [comment]
Yes thank you for creating this issue! Noticed this the other day. I'm guessing maybe something with the switch to websockets for api calls.

**Comment by psiinon** [comment]
Just fixed this for the new WebSockets PR with this line: https://github.com/zaproxy/zap-hud/blob/df1409ba3fa3a616929ccb9e31f21679a5b68373/src/main/zapHomeFiles/hud/display.js#L468
I'd expect the HTTP fix to be very similar

**Comment by dscrobonia** [comment]
Awesome! making sure payloads are being properly displayed in break is huge. Glad we can fix this soon. :)
