### ISSUE TITLE
Clone repo for first time, running runZap outputs errors but still works

### ISSUE THREAD

**Issue by dscrobonia** [zaproxy/zap-hud#434]
I tried seeing what it would be like for a first time user to clone the repo and try to run the HUD with the `./gradlew runZap` command. It took about 3 minutes to execute, and ultimately worked perfectly. But when the gradle CLI finished up it reported errors. 

I'm curious about why it reported errors but still worked. This may be confusing to first time users.

![image](https://user-images.githubusercontent.com/5150944/53604540-9f327600-3b69-11e9-8045-fdd0a0266b80.png)

**Comment by thc202** [comment]
The build expects ZAP to be up and running after 20 seconds (since it started it), in that case it took some more time to start. I guess we can give it more time, 60 seconds? That should be enough.

**Comment by dscrobonia** [comment]
also saw this heapDump

![image](https://user-images.githubusercontent.com/5150944/53604981-e79e6380-3b6a-11e9-8289-68ccb704db98.png)

**Comment by dscrobonia** [comment]
@thc202 just as an fyi, it took about 3 minutes from starting the command to have zap up and running. Is the 20 seconds just for one part of that? like after zap get downloaded  it waits 20 seconds from starting it til its open?

**Comment by thc202** [comment]
Yes, the 20s start counting just after starting the ZAP process.

Regarding the previous comment, that's Gradle daemon process:
https://docs.gradle.org/current/userguide/gradle_daemon.html

**Comment by dscrobonia** [comment]
oh interesting. is that an error then or just some weird config?

**Comment by thc202** [comment]
Just a config, it enables heap dumps when the Java process hits an OutOfMemoryError (if you were referring to that?).

**Comment by dscrobonia** [comment]
Thanks for explaining that to me @thc202 :D
