### ISSUE TITLE
Don't forget to turn off Vue eventBus listeners.

### ISSUE THREAD

**Issue by nothingismagick** [zaproxy/zap-hud#468]
You are making awesome use of the event listeners (e.g. here: https://github.com/zaproxy/zap-hud/blob/develop/src/main/zapHomeFiles/hud/display.js ), but best practice would suggest cleaning up your eventBus listeners with the beforeDestroy hook and calling `eventBus.$off`.

For your reference: https://vuejs.org/v2/api/#Instance-Methods-Events

**Comment by psiinon** [comment]
@nothingismagick thanks for letting us know! Most of us working on the HUD are pretty new to modern JS UI's so all feedback is much appreciated. So are PRs - so if you fancy showing how it should be done then please go ahead :D

**Comment by nothingismagick** [comment]
I absolutely love the HUD and am happy to contribute. Will make a PR las soon as I clean my plate - and plan on integrating this into the Quasar Framework's app extension family within our testing harnesses.

**Comment by psiinon** [comment]
Great! FYI we have a Google Group for the HUD here: https://groups.google.com/group/zaproxy-hud and a weekly Google Hangout - just let us know if you might like to join that and we'll send you an invite :)

**Comment by nothingismagick** [comment]
Closing this because of this issue I just linked and this https://github.com/zaproxy/zap-hud/pull/459#pullrequestreview-229465179 I just did.

**Comment by psiinon** [comment]
Reopening as its currently an issue and we dont know when #459 will be merged...
