### ISSUE TITLE
Feature request: open geckodriver / chromedriver with a CLI specified URL:PORT

### ISSUE THREAD

**Issue by nothingismagick** [zaproxy/zap-hud#478]
While resolving Issue #474 I discovered that there is no predetermined way to choose the driver or the port from the CLI. 

So, if I could have my way, I would love the command to be something like:
```
$ zap ./zap/ZAP_D-2019-04-29/zap.sh -daemon \ 
-host 127.0.0.1 -port 7777 -hud -nostdout
-driver firefox -url ${serverUrl}
```

I can verify, however, that my automated installation process for Quasar 1.0 works (at least on my Mac): https://github.com/quasarframework/quasar-testing/releases/tag/v1.0.0-beta.5

**Comment by nothingismagick** [comment]
Any idea if this will could possibly land before tomorrow's meeting? Would love to demo the Quasar integration I've set up here:

https://github.com/quasarframework/quasar-testing/blob/dev/packages/security/src/install.js#L97

**Comment by psiinon** [comment]
I'm trying to focus on ZAP things right now (which includes the HUD) so I'll see if I can make it so :)

**Comment by nothingismagick** [comment]
Can you give me an ETA on when I can pull he weekly with these changes?

**Comment by psiinon** [comment]
We've generated this weeks weekly, so the next one is planned for next Monday.
If you're ok installing java and gradle we can talk you through running the HUD in a dev version of ZAP with the latest changes...

**Comment by nothingismagick** [comment]
No point. It's not about me - it's for the automation of the app extension.
Then I'll wait to present it to you until it's available in the weekly.
