### ISSUE TITLE
Show changes in the HUD

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#535]
I suspect that most ZAP users dont read the change log.
I think it would be really useful to show the HUD specific changes actually in the HUD.
Ideally we would subtly highlight these and then clear that indication when the user has looked at the changes.
Options:

1. Add a Changes page to the Tutorial
1. Add a new Changelog icon next to the gear icon at the bottom
1. Add a new Changelog item to the options
1. ??

Whichever one we choose I think the relevant icon should have a star or plus which is cleared when the user visits that page / tool - we'd need to keep track of what the user has seen so that it can be enabled again for the next version

**Comment by dscrobonia** [comment]
I think this is a good idea.
- I prefer star over the plus. 
- I think the changelog should be very concise and only for big feature adds. I think showing too much will give folks notification fatigue.

Is there any reason we shouldn't just use the "News" section on ZAP desktop?

**Comment by psiinon** [comment]
Because thats in the ZAP desktop and not in the HUD :) We have loads of add-on and can already notify people if they are updated, I dont think we want to use the ZAP News section for this.
