### ISSUE TITLE
Flag changes in the HUD

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#553]
Follow up from #535
This issue is for flagging the changes in the HUD UI.
I've tried little plus and star icons but unfortunately I dont think they are very noticeable :(
![gear-plus](https://user-images.githubusercontent.com/1081115/61280235-d079ae80-a7b7-11e9-8661-4c16bc4ba65c.png) ![gear-star](https://user-images.githubusercontent.com/1081115/61280236-d1124500-a7b7-11e9-9ec6-c929c478d985.png)
I'm now thinking that we need a much bigger notification indicator. Will play around and post here...

**Comment by psiinon** [comment]
2 new attempts - I think we might need the bigger one for it to be noticeable:
![gear-exclamation](https://user-images.githubusercontent.com/1081115/61295010-68d35b80-a7d7-11e9-968a-8a4f43e2b685.png) ![gear-exclamation2](https://user-images.githubusercontent.com/1081115/61295011-696bf200-a7d7-11e9-935c-d54e2ef28443.png)
I'm now planning on showing this for both the changelog and the tutorial - the gear will keep the icon until the changelog and relevant tutorial pages have been accessed. Thoughts?

**Comment by kingthorin** [comment]
I like the big red exclamation mark.

**Comment by psiinon** [comment]
think I'm making good progress:
![config-new](https://user-images.githubusercontent.com/1081115/61390822-c8a33280-a8bb-11e9-8a18-9d4b5f937fd9.png)
![Tutoria-front-new](https://user-images.githubusercontent.com/1081115/61390823-c8a33280-a8bb-11e9-850f-283881073ba3.png)
![tutorial-index-new](https://user-images.githubusercontent.com/1081115/61390824-c8a33280-a8bb-11e9-8de6-8ae47e2cb1b9.png)

**Comment by psiinon** [comment]
the icons will all have hoverovers, eg "New content added"

**Comment by kingthorin** [comment]
Nice!
