### ISSUE TITLE
Support iframes

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#581]
The HUD does not currently show alerts or hidden fields (or comments) in iframes.
This is because the injected javascript only runs on the top frame.
Support for iframes would involve running similar injected code in the iframes and cascading commands from ZAP into them.
This might be non trivial, especially if the iframes are on a different domain :/

**Comment by thc202** [comment]
Duplicate of #138?

**Comment by psiinon** [comment]
Ugh, did a search but didnt find that for some reason :P
