### ISSUE TITLE
HUD frame breaks automated tests

### ISSUE THREAD

**Issue by jmakr0** [zaproxy/zap-hud#607]
Automated tests are broken when HUD is enabled (ZAP 2.8.0):
```
ElementClickInterceptedException: Message: Element <button class="positive" name="id" type="submit"> is not clickable at point (561,682) because another element <iframe id="zap-hud-bottom-drawer" src="https://zap//zapCallBackUrl/8648206587253027253/file/drawer.html?frameId=drawer&tabId=6754845-824"> obscures i
```
If I pause the execution before the submit and perform the click manually, everything is fine. Disabling HUD solves this problem, but still, that doesn't seem to be right.

**Comment by psiinon** [comment]
Why are you using the HUD with automated tests?
If you run the ZAP daemon then the HUD is disabled by default for this very reason - it will break automated tests as it changes the HTML.

**Comment by jmakr0** [comment]
Well, don't question this legacy setup here ;) Thank you very much for the quick response!
