### ISSUE TITLE
Add HUD HTTPS Warning

### ISSUE THREAD

**Issue by ossie-git** [zaproxy/zap-hud#637]
So I decided to try out HUD so I installed ZAP.  The first thing I did was enable HUD and configured my browser to use ZAP as a proxy.  I tried to connect to a vanilla HTTP site on my network and by browser failed to connect which was unexpected.  No errors showed up on the terminal and the History tab was empty.  When I connected to the ZAP port using telnet, it appeared to be running.

It was only after some head scratching and googling that I discovered that I had to first tell my browser to trust ZAP's Root CA and then enable HUD as HUD requires HTTPS, even if I was visiting a normal HTTP site.  So I disabled HUD, told my browser to trust the ROOT CA and went from there.

I'm not sure if this is documented anywhere, but I think it would be nice to give a popup to the user telling them to do the above before using HUD the first time so they don't waste time troubleshooting why nothing is working.  Thanks.

**Comment by psiinon** [comment]
@ossie-git is there any reason why you didnt click on the big 'Manual Explore' button and then use the 'Launch browser' option on the ZAP desktop?
If you do that the browser you launch is automatically proxied via ZAP and ignores cert warnings. Its much easier to get started that way.
This is kind of independent of the HUD, although the indications will be different.

**Comment by psiinon** [comment]
Theres also a big 'Learn More' button that takes you to the 'Getting Started Guide' which explains this is the best option.
Apart from really annoying popups (which most people wont want) I'm not sure what else we can do.
Suggestions on a postcard...
