### ISSUE TITLE
HUD broken with Firefox 74.0

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#701]
HUD is not shown on the first page visited (in this case a local bodgeit).
It appears when the next page is viewed, but HUD tools fail - nothing happens when you click on them.
Lots of Vue errors in the console: "SyntaxError: An invalid or illegal string was specified".
Initially reported vi the User Group: https://groups.google.com/d/msg/zaproxy-users/m-qH7lSao6E/KI2Q460kAgAJ
Chrome 80 appears to still work.

**Comment by psiinon** [comment]
It looks like the referrer value is not being set correctly, which could be due to either https://bugzilla.mozilla.org/show_bug.cgi?id=1601496 or https://bugzilla.mozilla.org/show_bug.cgi?id=1601743 :/

**Comment by psiinon** [comment]
Update - various of the HUD files use document.referrer:

- drawer.js
- display.js
- panel.js
- management.js

My current plan is to replace these with a constant and to inject the referrer taken from the header via ZAP.
Initial attempt got some of the HUD working (alerts) but not all of it - getting errors that the target origin provided doesnt match the recipient windows origin, so looks like I may have replaced too much?

**Comment by psiinon** [comment]
Interesting - I just tried a very simple test in FX 74 and the document.referrer element _is_ correct when linking between pages on one site. It also seems to work on https://whatismyreferer.com/
That implies theres something else going on I dont yet understand...

**Comment by psiinon** [comment]
I've been reminded that FX 74 introduced Enhanced Tracking Protection, which removed the referrer when tracking cookies are detected. This sounds possible, but I've just tried disabling ETP with the HUD but it still breaks :(

**Comment by dscrobonia** [comment]
Without having looked to deep into it, the idea is that one of our hacks of passing some info to the HUD from ZAP via the referer header is failing because FF is removing referer info?

**Comment by psiinon** [comment]
Yep, I think thats it :/

**Comment by dscrobonia** [comment]
I wonder if we can just pass it through via a GET or POST parameter and carve it out in the ServiceWorker's proxy capability...

**Comment by tavdog** [comment]
In the meantime, is there a last known version of FF that works ?  Nevermind, I just installed version 73 and the HUD is working.

**Comment by thc202** [comment]
The HUD stopped working when this change was introduced: https://bugzilla.mozilla.org/show_bug.cgi?id=1583700
(Nightly 20191023094816, changeset: https://hg.mozilla.org/mozilla-central/pushloghtml?changeset=ad7a152bc66c0d411a6fb0b210d675abed9693c7 )

Setting the preference `browser.tabs.documentchannel` to `false` restores the previous behaviour (i.e. referrer is set) and the HUD works again.

**Comment by psiinon** [comment]
A new version of the selenium add-on has now been released which fixes this.

**Comment by dfuentes77** [comment]
> A new version of the selenium add-on has now been released which fixes this.

I updated the selenium add-on and confirmed that it worked.

**Comment by psiinon** [comment]
FYI I've raise this bug on Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1626616

**Comment by tavdog** [comment]
I still can't get it to work in FF74. I've reverted to 73.01 and the HUD works perfectly if I launch it via ZAP, but launch FF via the system and manually setup proxy and certs, the HUD works mostly but it bugs out and the intercept button stops working and I can't delete items side bars.

**Comment by psiinon** [comment]
Oh yeah, if you launch Firefox manually then you'll needs to set the `browser.tabs.documentchannel` pref to `false` manually. The fix can only do that if you launch Firefox from ZAP.

**Comment by tavdog** [comment]
I have browser.tabs.documentchannel set to false. Without it the HUD doesn't AT ALL.  But even WITH that setting set false the hud still acts a little funny. Like the break icon doesn't turn red when clicked even though the request does get intercepted sometimes.  It seemed to be working well for a couple days then it started acting up. hmm.   Is there a way to get the zap launch to use a persistent profile so that I can have a few saved passwords in there ?
