### ISSUE TITLE
HUD issue on fresh install 

### ISSUE THREAD

**Issue by He5150** [zaproxy/zap-hud#736]
Hey everyone, I installed ZAP today, windows 10, 64 bit, firefox developer edition, no settings changed in zap. In firefox browser.urlbar.filter.javascript=false . network.proxy.allow_hijacking_localhost = True.

On load of the HUD option with a website inputted the HUD is partly shown. The plus symbols on either side and a blank bar on the lower part of the screen. The HUD doesn't respond to any input. Reset the HUD options, uninstalled and reinstalled. Also used on google chrome, same results. I checked the error log (is this through Help --> Support Info?) and no errors were populated. 

If I can do anything else to help out let me know, I'm going to keep playing around with it.

**Comment by psiinon** [comment]
Have you performed a 'check for updates' and updated all of the add-on?
The HUD uses browser features that often change when new versions of Firefox or Chrome are released. We do not go back and re-release a full version of ZAP everytime that happens, we just update the relevant ZAP add-ons.
In general its best to ask questions on the [ZAP HUD group](https://groups.google.com/group/zaproxy-hud) and only raise issues when you are sure that there is a bug.

**Comment by kingthorin** [comment]
Did you install ZAP's CA cert?

**Comment by He5150** [comment]
> 
> 
> Have you performed a 'check for updates' and updated all of the add-on?
> The HUD uses browser features that often change when new versions of Firefox or Chrome are released. We do not go back and re-release a full version of ZAP everytime that happens, we just update the relevant ZAP add-ons.
> In general its best to ask questions on the [ZAP HUD group](https://groups.google.com/group/zaproxy-hud) and only raise issues when you are sure that there is a bug.

I apologize for asking here, I wasn't 100% sure where to, I checked for updates on the app and all add ons, everything is up date.
I also installed the CA cert into Firefox. Still encountering the same issue, on load to the browser only those few overlays are present.

**Comment by kingthorin** [comment]
Oh have you actually navigated somewhere? I think on about:blank or the Firefox 'what's happening page' it won't load properly. Try going to example.com or something.

**Comment by He5150** [comment]
Yes sir. On the manual scan I’ve Inputted a target website, also navigated around to see if anything changes on the hud

**Comment by kingthorin** [comment]
Okay, it was worth a shot. I know I encountered that the first time I gave HUD a whirl.

**Comment by kingthorin** [comment]
If you launch Firefox from ZAP does it work? There may be another setting we're overlooking that ZAP/Selenium applies when launched from within ZAP.

**Comment by He5150** [comment]
Yeah If I launch firefox from zap through the tool bar up top it works. No Hud appears as well but I'm not sure If it's suppose to.

**Comment by kingthorin** [comment]
Yes if HUD is enabled and you launch a browser from the toolbar it should work. Would you be willing to install "normal" Firefox to see if it's something specific to the devloper version?

**Comment by He5150** [comment]
Yes definitely can! I'll report back if anything changes

**Comment by He5150** [comment]
> 
> 
> Yes if HUD is enabled and you launch a browser from the toolbar it should work. Would you be willing to install "normal" Firefox to see if it's something specific to the devloper version?

Must have been something with the developer version, Hud loaded right up on start of regular firefox. I guess I should have tried that first.

Again apologies for posting this thread here

**Comment by kingthorin** [comment]
Thanks for letting us know 👍

**Comment by He5150** [comment]
Of course! Hopefully it helps
