### ISSUE TITLE
Informational alert "HUD Tutorial page Alert" not displayed

### ISSUE THREAD

**Issue by MattPlum** [zaproxy/zap-hud#771]
I am learning OWASP ZAP and doing the HUD tutorial. But I cannot get past the Page Alerts section because the alert with the key is not coming up. Running Windows 7 Firefox

![image](https://user-images.githubusercontent.com/21339664/85880624-4fd67700-b7aa-11ea-8d3b-c8cba0a25f8f.png)

**Comment by psiinon** [comment]
Thats strange. What do you see when you click on the Info level Site Alert icon on the right hand side? The site level alerts are a super set. But I dont know why its not being shown at the Page Level :/

**Comment by MattPlum** [comment]
![image](https://user-images.githubusercontent.com/21339664/85884203-405a2c80-b7b0-11ea-9e39-7d84dfb1d4dd.png)
its a timestamp alert

**Comment by thc202** [comment]
Those are the Site alerts not the Page alerts.

You can skip the task by enabling Options > HUD >Skip tutorial tasks.
https://www.zaproxy.org/docs/desktop/addons/hud/options/#skip-tutorial-tasks

**Comment by MattPlum** [comment]
Yesi know, @psiinon asked to see the site alerts. I ran it on Chrome and it worked fine, so must have been a firefox windows 7 bug . thanks

**Comment by thc202** [comment]
Sorry, should have paid more attention. It would be great if you could check if there was any error in the browser when that happened. What Firefox version were you using?

**Comment by dkuku** [comment]
![2020-10-15-181418_1920x1080_scrot](https://user-images.githubusercontent.com/904179/96163791-3e100f80-0f12-11eb-8bcd-cdaad10c7cd0.png)
I got this problem too
