### ISSUE TITLE
ZAP not working with geckodriver version 0.27.0

### ISSUE THREAD

**Issue by mayhem-am** [zaproxy/zap-hud#865]
If ZAP is not proxying after release 2.10, it is because of the geckodriver version 0.27.0 it comes bundled with. Downgrading to 0.24.0 which is known to be supported is a viable fix for the issue.

**Comment by thc202** [comment]
The above comment is not correct, ZAP 2.10 bundles version 0.28.0.

Usage problems/questions are better handled in the [Users Group](https://groups.google.com/group/zaproxy-users).
